import java.awt.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Gautham S Panicker
 */
public class ChatBOX extends javax.swing.JFrame {

    /**
     * Creates new form ChatBOX
     */
    public ChatBOX() {
        String id="1";
        setUndecorated(true);
        initComponents();
        
        setBackground(new Color(1.0f,1.0f,1.0f,0.0f));
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        hmbtn = new javax.swing.JButton();
        navbtn = new javax.swing.JButton();
        abtbtn = new javax.swing.JButton();
        stnsbtn = new javax.swing.JButton();
        clsbtn = new javax.swing.JButton();
        chbtn1 = new javax.swing.JButton();
        lbx05 = new javax.swing.JLabel();
        lbx01 = new javax.swing.JLabel();
        lbx02 = new javax.swing.JLabel();
        lbx03 = new javax.swing.JLabel();
        lbx04 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1100, 660));
        setPreferredSize(new java.awt.Dimension(1100, 660));
        getContentPane().setLayout(null);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        hmbtn.setContentAreaFilled(false);
        jPanel1.add(hmbtn);
        hmbtn.setBounds(54, 183, 58, 58);

        navbtn.setContentAreaFilled(false);
        jPanel1.add(navbtn);
        navbtn.setBounds(54, 350, 58, 58);

        abtbtn.setContentAreaFilled(false);
        jPanel1.add(abtbtn);
        abtbtn.setBounds(54, 434, 58, 58);

        stnsbtn.setContentAreaFilled(false);
        jPanel1.add(stnsbtn);
        stnsbtn.setBounds(54, 518, 58, 58);

        clsbtn.setContentAreaFilled(false);
        clsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clsbtnActionPerformed(evt);
            }
        });
        jPanel1.add(clsbtn);
        clsbtn.setBounds(1017, 0, 43, 43);

        chbtn1.setContentAreaFilled(false);
        jPanel1.add(chbtn1);
        chbtn1.setBounds(54, 259, 58, 58);

        lbx05.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        lbx05.setForeground(new java.awt.Color(0, 0, 51));
        jPanel1.add(lbx05);
        lbx05.setBounds(160, 550, 270, 90);

        lbx01.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        lbx01.setForeground(new java.awt.Color(0, 0, 51));
        lbx01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbx01MouseClicked(evt);
            }
        });
        jPanel1.add(lbx01);
        lbx01.setBounds(160, 190, 270, 90);

        lbx02.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        lbx02.setForeground(new java.awt.Color(0, 0, 51));
        jPanel1.add(lbx02);
        lbx02.setBounds(160, 280, 270, 90);

        lbx03.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        lbx03.setForeground(new java.awt.Color(0, 0, 51));
        jPanel1.add(lbx03);
        lbx03.setBounds(160, 370, 270, 90);

        lbx04.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        lbx04.setForeground(new java.awt.Color(0, 0, 51));
        jPanel1.add(lbx04);
        lbx04.setBounds(160, 460, 270, 90);

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(150, 80, 280, 40);

        jTextField1.setBackground(new java.awt.Color(139, 142, 171));
        jTextField1.setBorder(null);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(170, 140, 210, 16);

        jTextArea1.setBackground(new java.awt.Color(165, 173, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(450, 120, 570, 440);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1060, 660);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Chat.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(650, 1100));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1100, 660);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbx01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbx01MouseClicked
        System.out.println("Clicked");
    }//GEN-LAST:event_lbx01MouseClicked

    private void clsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clsbtnActionPerformed
      System.exit(0);
    }//GEN-LAST:event_clsbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatBOX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatBOX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatBOX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatBOX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChatBOX().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abtbtn;
    private javax.swing.JButton chbtn1;
    private javax.swing.JButton clsbtn;
    private javax.swing.JButton hmbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lbx01;
    private javax.swing.JLabel lbx02;
    private javax.swing.JLabel lbx03;
    private javax.swing.JLabel lbx04;
    private javax.swing.JLabel lbx05;
    private javax.swing.JButton navbtn;
    private javax.swing.JButton stnsbtn;
    // End of variables declaration//GEN-END:variables
}
