
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.*;
import java.sql.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Gautham S Panicker
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        setUndecorated(true);
        initComponents();
        setSize(730,800);
        
        setBackground(new Color(1.0f,1.0f,1.0f,0.0f));
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(50,50);
    }
    
    public String connect(String em,String pw) {
            
            String ret="yes";
            try {
            // Connect method #1
            String dbURL1 = "jdbc:postgresql://bufgicasqaqo7bwrsl3h-postgresql.services.clever-cloud.com:5432/bufgicasqaqo7bwrsl3h?user=uhzvhtgjrq3nerli7qvm&password=RSpBNrIHs9hgGP0yysYx";
            Connection conn1 = DriverManager.getConnection(dbURL1);
            Statement statement = conn1.createStatement();
            ResultSet resultSet = statement.executeQuery("select uid from sync_main where email='"+em+"' and password='"+pw+"'");
            if (!resultSet.next())
                    ret="no";
            else
                ret=resultSet.getString(1);
            
            conn1.close();
    
                    } catch (SQLException ex) {
            ex.printStackTrace();
        }   
//            String[] out_ncount={out,String.format("%d", count)};
//            return out_ncount;
            return ret;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField2 = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        Sign_up = new javax.swing.JButton();
        Sign_in1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        dvsd = new javax.swing.JTextField();
        ppf = new javax.swing.JPasswordField();
        etf1 = new javax.swing.JTextField();
        etf = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jPasswordField2.setText("jPasswordField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setOpaque(false);

        Sign_up.setBorder(null);
        Sign_up.setContentAreaFilled(false);
        Sign_up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sign_upActionPerformed(evt);
            }
        });

        Sign_in1.setContentAreaFilled(false);
        Sign_in1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sign_in1ActionPerformed(evt);
            }
        });

        jPanel2.setOpaque(false);
        jPanel2.setLayout(null);

        dvsd.setBackground(new java.awt.Color(2, 8, 41));
        dvsd.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        dvsd.setForeground(new java.awt.Color(255, 255, 255));
        dvsd.setText("Email");
        dvsd.setBorder(null);
        jPanel2.add(dvsd);
        dvsd.setBounds(10, 20, 342, 30);

        ppf.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        jPanel2.add(ppf);
        ppf.setBounds(10, 120, 342, 30);

        etf1.setBackground(new java.awt.Color(2, 8, 41));
        etf1.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        etf1.setForeground(new java.awt.Color(255, 255, 255));
        etf1.setText("Password");
        etf1.setBorder(null);
        jPanel2.add(etf1);
        etf1.setBounds(10, 90, 342, 30);

        etf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etfActionPerformed(evt);
            }
        });
        jPanel2.add(etf);
        etf.setBounds(10, 50, 340, 30);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(190, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Sign_in1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(287, 287, 287))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Sign_up, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(249, 249, 249))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(167, 167, 167))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(261, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(Sign_in1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(Sign_up, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 730, 730);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/login.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 730, 730);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Sign_upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sign_upActionPerformed
        this.dispose();
        new testeter("Gautham").setVisible(true);

JOptionPane.showMessageDialog(this, "Please ensure compliance!","Swing Tester", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_Sign_upActionPerformed

    private void Sign_in1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sign_in1ActionPerformed
        String em=etf.getText(),pw=ppf.getText();
//        System.out.println("yes");
        String ret=connect(em,pw);
        
        if (ret=="no")
        {
            JOptionPane.showMessageDialog(this, "Invalid Email or Password!","Invalid", JOptionPane.WARNING_MESSAGE);
        }
        else{
            this.dispose();
//            new Main_Page("Gautham").setVisible(true);
        
        }
        
        
    }//GEN-LAST:event_Sign_in1ActionPerformed

    private void etfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Sign_in1;
    private javax.swing.JButton Sign_up;
    private javax.swing.JTextField dvsd;
    private javax.swing.JTextField etf;
    private javax.swing.JTextField etf1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField ppf;
    // End of variables declaration//GEN-END:variables
}
