
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;



/**
 *
 * @author Gautham S Panicker
 */
public class Main_Page extends javax.swing.JFrame {

    /**
     * Creates new form Quo
     */
    String uid="0",quid="";
    public Main_Page() {
        uid="1";
        setUndecorated(true);
        initComponents();
        Hi.setText("Hi,"+connect());
//        postquery.setText("Post your query here");
        question();
        setBackground(new Color(1.0f,1.0f,1.0f,0.0f));
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        
    }
    
     public String connect() {
            
            String ret="yes";
            try {
            // Connect method #1
            String dbURL1 = "jdbc:postgresql://bufgicasqaqo7bwrsl3h-postgresql.services.clever-cloud.com:5432/bufgicasqaqo7bwrsl3h?user=uhzvhtgjrq3nerli7qvm&password=RSpBNrIHs9hgGP0yysYx";
                try (Connection conn1 = DriverManager.getConnection(dbURL1)) {
                    Statement statement = conn1.createStatement();
                    ResultSet resultSet = statement.executeQuery("select username from sync_main where uid='"+uid+"'");
                    if (!resultSet.next())
                        ret="no";
                    else
                        ret=resultSet.getString(1);
                    conn1.close();
                    
                }
    
                    } catch (SQLException ex) {
                         ex.printStackTrace();
        }    
            return ret;
   
        }   
     public void question(){
         String ret="yes";
            try {
            // Connect method #1
            String dbURL1 = "jdbc:postgresql://bufgicasqaqo7bwrsl3h-postgresql.services.clever-cloud.com:5432/bufgicasqaqo7bwrsl3h?user=uhzvhtgjrq3nerli7qvm&password=RSpBNrIHs9hgGP0yysYx";
                try (Connection conn1 = DriverManager.getConnection(dbURL1)) {
                    Statement statement = conn1.createStatement();
                    ResultSet resultSet = statement.executeQuery("select queastion,quid from queastion ;");
                    int i=0;
                    while(resultSet.next()){
                        switch (i){
                            case 0:ques1.setText(resultSet.getString(1));
                            quid=resultSet.getString(2);
                            break;
                            case 1:ques2.setText(resultSet.getString(1));break;
                            case 2:ques3.setText(resultSet.getString(1));break;
                            case 3:ques4.setText(resultSet.getString(1));break;
                            case 4:ques5.setText(resultSet.getString(1));break;
                        
                        }
//                         System.out.println(resultSet.getString(1));
//                         ques1.setText(resultSet.getString(1));
                        i++;
                    
                    
                    }
                                
               
                    conn1.close();
                    
                }
                    } catch (SQLException ex) {
                         ex.printStackTrace();
        }            
            
     }
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ques3 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        ques1 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        ques5 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        ques2 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        ques4 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        Hi = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        postquery = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        closebtn = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1100, 650));
        getContentPane().setLayout(null);

        jPanel2.setOpaque(false);

        jPanel1.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        jPanel1.setOpaque(false);

        ques3.setBackground(new java.awt.Color(204, 204, 204));
        ques3.setColumns(20);
        ques3.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        ques3.setRows(5);
        ques3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ques3MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(ques3);

        jScrollPane3.setBorder(null);
        jScrollPane3.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        jScrollPane3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane3MouseClicked(evt);
            }
        });

        ques1.setBackground(new java.awt.Color(204, 204, 204));
        ques1.setColumns(20);
        ques1.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        ques1.setRows(5);
        ques1.setBorder(null);
        ques1.setOpaque(false);
        ques1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ques1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(ques1);

        ques5.setColumns(20);
        ques5.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        ques5.setRows(5);
        ques5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ques5MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(ques5);

        ques2.setBackground(new java.awt.Color(204, 204, 204));
        ques2.setColumns(20);
        ques2.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        ques2.setRows(5);
        ques2.setBorder(null);
        ques2.setOpaque(false);
        ques2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ques2MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(ques2);

        ques4.setColumns(20);
        ques4.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        ques4.setRows(5);
        ques4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ques4MouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(ques4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        jScrollPane1.setViewportView(jPanel1);

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("WELCOME BACK, LET' SYNC IN!");

        Hi.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 36)); // NOI18N
        Hi.setForeground(new java.awt.Color(255, 255, 255));
        Hi.setText("WELCOME ");

        jLabel3.setText("Search");

        postquery.setEditable(false);
        postquery.setBackground(new java.awt.Color(204, 204, 204));
        postquery.setFont(new java.awt.Font("Franklin Gothic Medium", 2, 21)); // NOI18N
        postquery.setText("  Post your query here");
        postquery.setBorder(null);
        postquery.setOpaque(false);
        postquery.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                postqueryFocusGained(evt);
            }
        });
        postquery.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                postqueryMouseClicked(evt);
            }
        });
        postquery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postqueryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
                            .addComponent(Hi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(122, 122, 122)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(postquery, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(239, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Hi, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(postquery, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1040, 650);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/anu rgemer.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1100, 650);

        closebtn.setText("jButton1");
        closebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebtnActionPerformed(evt);
            }
        });
        getContentPane().add(closebtn);
        closebtn.setBounds(1019, -5, 40, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ques4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ques4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ques4MouseClicked

    private void ques2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ques2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ques2MouseClicked

    private void ques5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ques5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ques5MouseClicked

    private void ques1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ques1MouseClicked
       // TODO add your handling code here:
    }//GEN-LAST:event_ques1MouseClicked

    private void ques3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ques3MouseClicked
        
            System.out.println("Clicked");
       this.dispose();
       new Quo(quid).setVisible(true);
    }//GEN-LAST:event_ques3MouseClicked

    private void jScrollPane3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane3MouseClicked

    private void closebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closebtnActionPerformed

    private void postqueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postqueryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_postqueryActionPerformed

    private void postqueryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_postqueryMouseClicked
       //if (postquery.getText()=="Post your query here")
           postquery.setText("");
    }//GEN-LAST:event_postqueryMouseClicked

    private void postqueryFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_postqueryFocusGained
        // TODO add your handling code here:
//        if (postquery.getText()=="Post your query here")
//           postquery.setText("");
    }//GEN-LAST:event_postqueryFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Main_Page().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Hi;
    private javax.swing.JButton closebtn;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextField postquery;
    private javax.swing.JTextArea ques1;
    private javax.swing.JTextArea ques2;
    private javax.swing.JTextArea ques3;
    private javax.swing.JTextArea ques4;
    private javax.swing.JTextArea ques5;
    // End of variables declaration//GEN-END:variables

    
}