
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;



/**
 *
 * @author Gautham S Panicker
 */
public class Quo extends javax.swing.JFrame {

    /**
     * Creates new form Quo
     */

    public Quo(String quid) {
        setUndecorated(true);
        initComponents();
       setBackground(new Color(1.0f,1.0f,1.0f,0.0f));
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        
    }
    
    
            
     
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        question = new javax.swing.JTextField();
        home = new javax.swing.JButton();
        chat = new javax.swing.JButton();
        map = new javax.swing.JButton();
        closebtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        quora = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1100, 650));
        getContentPane().setLayout(null);

        question.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 20)); // NOI18N
        question.setText("What is some college advice for a btech 2nd year?");
        question.setBorder(null);
        question.setOpaque(false);
        question.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questionActionPerformed(evt);
            }
        });
        getContentPane().add(question);
        question.setBounds(180, 160, 480, 50);

        home.setText("jButton1");
        getContentPane().add(home);
        home.setBounds(50, 180, 60, 50);

        chat.setText("jButton2");
        getContentPane().add(chat);
        chat.setBounds(50, 260, 60, 60);

        map.setText("jButton3");
        getContentPane().add(map);
        map.setBounds(50, 340, 60, 70);

        closebtn.setText("jButton1");
        closebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebtnActionPerformed(evt);
            }
        });
        getContentPane().add(closebtn);
        closebtn.setBounds(1010, -5, 60, 50);

        jPanel1.setOpaque(false);

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setText("Hi.\n\nI just completed my second year of BTech, So I feel I can answer this question well.\n\nSecond year of college is pretty much the tone setter of your college life, this is the year when you actually have to decide that what are you going to do after your College. Then this is the year when you can experiment with different things without the fear of failing because even if that happens then you'll have decent amount of time to fix it. Since I am a Btech Student, so speaking particularly about it this is the time when you have to try out different things so that you get to know whether you want to ahead with your Tech skills or you want to take a Non Tech job in future. 2nd year is the year to try out things, you may not be good at your subjects or the stream in which you're pursuing your degree, it's okay, that's not an issue, but that can only be said if you try. For BTech students, 2nd year is the year when they should actually start focussing on their Technical skills because as the years keep on passing thing get difficult.\n\nThese were some of the points that I could come up with, I hope they will help in some way or the other.\n\nThanks.");
        jTextArea2.setOpaque(false);
        jScrollPane1.setViewportView(jTextArea2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(455, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(302, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1100, 660);

        quora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/anu rgemer.jpg"))); // NOI18N
        quora.setText("jdf");
        quora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quoraMouseClicked(evt);
            }
        });
        getContentPane().add(quora);
        quora.setBounds(0, 0, 1100, 650);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void questionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_questionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_questionActionPerformed

    private void quoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quoraMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_quoraMouseClicked

    private void closebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Main_Page().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chat;
    private javax.swing.JButton closebtn;
    private javax.swing.JButton home;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JButton map;
    private javax.swing.JTextField question;
    private javax.swing.JLabel quora;
    // End of variables declaration//GEN-END:variables

    
}